import { ConfigContext, ExpoConfig } from 'expo/config'
import { execSync } from 'node:child_process'

import packageJson from './package.json'
import nativeAccents from './src/containers/ThemeService/themes/native-accents.json'

/**
 * Build identity, shown on the About screen and put in the feedback email
 * subject so a user report can be tied back to exact code.
 *
 * Resolution order, most authoritative first:
 *   1. `EAS_BUILD_GIT_COMMIT_HASH` — the commit EAS Build checked out.
 *   2. `GITHUB_SHA` — set in Actions, and unlike the above it is also present
 *      for `eas update`, which is how most users receive a JS change.
 *   3. Local git HEAD, suffixed `-dirty` when the tree has uncommitted work.
 *   4. A timestamp, only when git is unavailable.
 *
 * Memoised: Metro re-evaluates this config per request, and a tag that changed
 * between evaluations would report a different build for identical code.
 */
let buildTag: string | undefined

const git = (command: string) =>
  execSync(command, { stdio: ['ignore', 'pipe', 'ignore'] })
    .toString()
    .trim()

function resolveBuildTag(): string {
  if (buildTag) {
    return buildTag
  }

  const fromCi = process.env.EAS_BUILD_GIT_COMMIT_HASH || process.env.GITHUB_SHA
  if (fromCi) {
    buildTag = `#${fromCi.slice(0, 7)}`
    return buildTag
  }

  try {
    const head = git('git rev-parse --short=7 HEAD')
    const dirty = git('git status --porcelain') !== ''
    buildTag = `#${head}${dirty ? '-dirty' : ''}`
  } catch {
    buildTag = new Date().toISOString()
  }
  return buildTag
}

// Themes with a dedicated app icon (generated by
// scripts/generate-theme-icons.mjs); `r2v` uses the primary icon.
const ICON_THEMES = [
  'gin_blue',
  'gin_dark_purple',
  'gin_purple',
  'gin_green',
  'gin_teal',
  'gin_red',
  'gin_orange',
  'gin_yellow',
  'gin_pink',
]

export default ({ config }: ConfigContext): ExpoConfig => {
  const merged = {
    ...config,
    name: 'R2V',
    slug: 'v2ex-react-native',
    icon: './src/assets/icons/icon-r2v-light.png',
    userInterfaceStyle: 'automatic',
    scheme: 'r2v',
    jsEngine: 'hermes',
    // Android `colorPrimary`, which otherwise defaults to Expo's #023c69 — a
    // blue used nowhere in the app. This is only the pre-JS baseline; once the
    // theme loads, modules/accent-color points the activity theme at the
    // active accent (see plugins/withThemeAccentColors).
    primaryColor: nativeAccents.r2v.light,
    updates: {
      fallbackToCacheTimeout: 0,
      url: 'https://u.expo.dev/5c24d369-c0ba-41e3-8679-8b8cee82fc13',
    },
    assetBundlePatterns: ['**/*'],
    ios: {
      supportsTablet: true,
      bundleIdentifier: 'com.kucial.v2ex',
      appleTeamId: 'HVCHYVPAAC',
      runtimeVersion: packageJson.version.split('.').slice(0, -1).join('.'),
      icon: './src/assets/r2v-icon.icon',
      splash: {
        image: './src/assets/splash.png',
        backgroundColor: '#ffffff',
        dark: {
          image: './src/assets/splash-dark.png',
          backgroundColor: '#111111',
        },
      },
      infoPlist: {
        CFBundleDevelopmentRegion: 'zh-hans',
        ITSAppUsesNonExemptEncryption: false,
        UIBackgroundModes: ['audio'],
      },
      entitlements: {
        'com.apple.security.application-groups': ['group.com.kucial.v2ex.data'],
      },
    },
    android: {
      adaptiveIcon: {
        foregroundImage: './src/assets/adaptive-icon.png',
        backgroundColor: '#FFFFFF',
      },
      splash: {
        image: './src/assets/splash-icon.png',
        backgroundColor: '#ffffff',
        resizeMode: 'contain',
        dark: {
          image: './src/assets/splash-dark-icon.png',
          resizeMode: 'contain',
          backgroundColor: '#111111',
        },
      },
      package: 'com.kucial.v2ex',
    },
    extra: {
      eas: {
        projectId: '5c24d369-c0ba-41e3-8679-8b8cee82fc13',
      },
      IOS_APP_ID: process.env.IOS_APP_ID,
      SENTRY_DSN: process.env.SENTRY_DSN,
      IMGUR_CLIENT_ID: process.env.IMGUR_CLIENT_ID,
      ANALYTICS_INGEST_URL: process.env.ANALYTICS_INGEST_URL,
      ANALYTICS_INGEST_KEY: process.env.ANALYTICS_INGEST_KEY,
      // env vars are strings; coerce here so `@/env` can expose a real boolean
      ANALYTICS_DEBUG_INGEST: process.env.ANALYTICS_DEBUG_INGEST === '1',
      buildTag: resolveBuildTag(),
    },
    appRouter: {
      root: './src/app',
    },
    experiments: {
      typedRoutes: true,
      reactCompiler: true,
    },
    plugins: [
      [
        'expo-asset',
        {
          assets: ['./src/assets/images', './src/assets/brand_icons'],
        },
      ],
      '@sentry/react-native',
      './plugins/withSkipLocalSentryUpload',
      './plugins/withFixShadowNodeRaceCondition',
      './plugins/withThemeAccentColors',
      'expo-image',
      'expo-splash-screen',
      'expo-status-bar',
      'expo-secure-store',
      'expo-image-picker',
      'expo-audio',
      'expo-router',
      'expo-build-properties',
      'expo-web-browser',
      'expo-background-task',
      '@bacons/apple-targets',
      [
        './plugins/withAlternateAppIcons',
        {
          icons: ICON_THEMES.map(
            (theme) => `./src/assets/icons/composer/AppIcon-${theme}.icon`,
          ),
        },
      ],
    ],
  }

  return merged as ExpoConfig
}
