const {
  WarningAggregator,
  withMainApplication,
} = require('expo/config-plugins')

/**
 * Enables the React Native feature flag `fixFindShadowNodeByTagRaceCondition`
 * on Android.
 *
 * Fixes Sentry V2EX-REACT-NATIVE-EF: a SIGSEGV inside
 * `ShadowTreeRegistry::enumerate`, reached from
 * `FabricUIManagerBinding::findNextFocusableElement` when Android runs a
 * directional focus search (hardware keyboard Tab/arrows, D-pad, tablet mouse)
 * inside a ReactScrollView.
 *
 * Root cause: the unflagged path of `UIManager::findShadowNodeByTag_DEPRECATED`
 * captures a raw `RootShadowNode*` from `tryCommit()` and dereferences it after
 * the commit is cancelled, so a concurrent commit or surface stop can free it
 * mid-traversal. RN 0.86 ships the fix (`getCurrentRevision()`, which keeps the
 * root alive via shared_ptr) but the flag still defaults to false.
 *
 * `loadReactNative(this)` — generated by the RN gradle plugin — already calls
 * `ReactNativeFeatureFlags.override(...)` with the release-level provider, and a
 * second `override()` throws ("Feature flags cannot be overridden more than
 * once"). So we force-override on top of it instead. The provider subclasses
 * `ReactNativeNewArchitectureFeatureFlagsDefaults`, which is exactly what the
 * stable release level installs.
 *
 * Remove this plugin once React Native flips the flag on by default — worth
 * re-checking on every Expo SDK / RN bump.
 */

const MARKER = 'fixFindShadowNodeByTagRaceCondition'

const IMPORTS = [
  'import android.util.Log',
  'import com.facebook.react.internal.featureflags.ReactNativeFeatureFlags',
  'import com.facebook.react.internal.featureflags.ReactNativeNewArchitectureFeatureFlagsDefaults',
]

const LOAD_CALL = 'loadReactNative(this)'

const OVERRIDE_BLOCK = `    // Sentry V2EX-REACT-NATIVE-EF: SIGSEGV in ShadowTreeRegistry::enumerate, reached from
    // FabricUIManagerBinding::findNextFocusableElement. RN 0.86 ships the fix for the
    // findShadowNodeByTag_DEPRECATED use-after-free behind a flag that still defaults to
    // false. loadReactNative() has already installed the release-level override, so we
    // force-override on top of it. Injected by plugins/withFixShadowNodeRaceCondition.js.
    ReactNativeFeatureFlags.dangerouslyForceOverride(
        object : ReactNativeNewArchitectureFeatureFlagsDefaults() {
          override fun ${MARKER}(): Boolean = true
        }
    )?.let { Log.w("MainApplication", "RNFF accessed before override: $it") }`

function withFixShadowNodeRaceCondition(config) {
  return withMainApplication(config, (config) => {
    if (config.modResults.language !== 'kt') {
      WarningAggregator.addWarningAndroid(
        'withFixShadowNodeRaceCondition',
        `MainApplication is ${config.modResults.language}, not Kotlin; skipping the ${MARKER} override.`,
      )
      return config
    }

    let contents = config.modResults.contents

    // Idempotent: prebuild can run against an already-patched file.
    if (contents.includes(MARKER)) {
      return config
    }

    const loadIndex = contents.indexOf(LOAD_CALL)
    if (loadIndex === -1) {
      WarningAggregator.addWarningAndroid(
        'withFixShadowNodeRaceCondition',
        `Could not find \`${LOAD_CALL}\` in MainApplication.kt; the ${MARKER} override was not applied. The Expo template likely changed — update plugins/withFixShadowNodeRaceCondition.js.`,
      )
      return config
    }

    const missingImports = IMPORTS.filter(
      (statement) => !contents.includes(statement),
    )
    if (missingImports.length) {
      const anchor = '\nimport expo.modules.'
      const anchorIndex = contents.indexOf(anchor)
      if (anchorIndex === -1) {
        WarningAggregator.addWarningAndroid(
          'withFixShadowNodeRaceCondition',
          `Could not find an import anchor in MainApplication.kt; the ${MARKER} override was not applied.`,
        )
        return config
      }
      contents =
        contents.slice(0, anchorIndex) +
        '\n' +
        missingImports.join('\n') +
        '\n' +
        contents.slice(anchorIndex)
    }

    // Insert right after `loadReactNative(this)` — recompute the index, the
    // import splice above shifted it.
    const endOfLoadLine = contents.indexOf(LOAD_CALL) + LOAD_CALL.length
    contents =
      contents.slice(0, endOfLoadLine) +
      '\n' +
      OVERRIDE_BLOCK +
      contents.slice(endOfLoadLine)

    config.modResults.contents = contents
    return config
  })
}

module.exports = withFixShadowNodeRaceCondition
