import AccentColorModule from './src/AccentColorModule'

export type AccentVariant = 'light' | 'dark' | 'pure_dark'

/**
 * Name of the Android style resource carrying a theme+variant accent.
 *
 * Must match the names generated by `plugins/withThemeAccentColors.js`.
 * Deliberately underscore-separated: `R.style` rewrites dots in resource names
 * to underscores, and `Resources.getIdentifier` would then fail to find a
 * dotted name at runtime.
 */
export function androidAccentStyle(
  theme: string,
  variant: AccentVariant,
): string {
  return `app_accent_${theme}_${variant}`
}

/**
 * Point the native accent at the active theme.
 *
 * iOS uses `hex` for the window tint; Android resolves the generated style. A
 * `false` return means nothing was applied — an unparseable colour, a style
 * this binary does not have, or no foreground activity. Callers treat that as
 * cosmetic and carry on.
 */
export function setAccentColor(
  hex: string,
  theme: string,
  variant: AccentVariant,
): boolean {
  return AccentColorModule.setAccentColor(
    hex,
    androidAccentStyle(theme, variant),
  )
}

export default AccentColorModule
